#!/usr/bin/python3
#type: ignore

from mesa.visualization.ModularVisualization import ModularServer
from mesa.visualization.modules import CanvasGrid
from logica import *


# FIXME: Arreglar Persona
def agent_portrayal(agent):
    if agent is None:
        return

    if isinstance(agent, Car):
        portrayal = {
            "Shape": "circle", "Filled": "true", "Layer": 1, "Color": "red", "r": 0.5
        }
    elif isinstance(agent, Building):
        portrayal = {
            "Shape": "rect", "Filled": "true", "Layer": 0, "Color": agent.color, "w": 1, "h": 1
        }
        if agent.number is not None:
            portrayal["text"] = str(agent.number)
            portrayal["text_color"] = "black"
    elif isinstance(agent, RoadSign):
        portrayal = {
            "Shape": "rect", "Filled": "true", "Layer": 0, "Color": agent.color, "w": 1, "h": 1,
            "text": agent.direction, "text_color": "white"
        }
    else:
        portrayal = {
            "Shape": "rect", "Filled": "true", "Layer": 0, "Color": "#FFFFFF", "w": 1, "h": 1
        }
    return portrayal


grid_width = 24
grid_height = 24
canvas_element = CanvasGrid(agent_portrayal, grid_width, grid_height, 590, 590)


# Lista de edificios
buildings_info = [
    {"width": 3, "height": 4, "x": 2, "y": 18, "color": "#0000FF"},
    {"width": 5, "height": 4, "x": 7, "y": 18, "color": "#0000FF"},
    {"width": 2, "height": 10, "x": 16, "y": 12, "color": "#0000FF"},
    {"width": 2, "height": 10, "x": 20, "y": 12, "color": "#0000FF"},
    {"width": 10, "height": 4, "x": 2, "y": 12, "color": "#0000FF"},
    {"width": 4, "height": 2, "x": 2, "y": 6, "color": "#0000FF"},
    {"width": 4, "height": 2, "x": 2, "y": 2, "color": "#0000FF"},
    {"width": 4, "height": 6, "x": 8, "y": 2, "color": "#0000FF"},
    {"width": 2, "height": 2, "x": 13, "y": 9, "color": "#A52A2A"},
    {"width": 2, "height": 2, "x": 16, "y": 6, "color": "#0000FF"},
    {"width": 2, "height": 2, "x": 20, "y": 6, "color": "#0000FF"},
    {"width": 2, "height": 2, "x": 20, "y": 2, "color": "#0000FF"},
    {"width": 2, "height": 2, "x": 16, "y": 2, "color": "#0000FF"},
]

# Lista de estacionamientos
specials_info = [
    {"width": 1, "height": 1, "x": 4, "y": 19, "color": "#FFFF00", "number": 3},
    {"width": 1, "height": 1, "x": 8, "y": 21, "color": "#FFFF00", "number": 1},
    {"width": 1, "height": 1, "x": 11, "y": 19, "color": "#FFFF00", "number": 4},
    {"width": 1, "height": 1, "x": 17, "y": 20, "color": "#FFFF00", "number": 2},
    {"width": 1, "height": 1, "x": 20, "y": 19, "color": "#FFFF00", "number": 5},
    {"width": 1, "height": 1, "x": 16, "y": 13, "color": "#FFFF00", "number": 10},
    {"width": 1, "height": 1, "x": 21, "y": 14, "color": "#FFFF00", "number": 8},
    {"width": 1, "height": 1, "x": 11, "y": 13, "color": "#FFFF00", "number": 9},
    {"width": 1, "height": 1, "x": 9, "y": 15, "color": "#FFFF00", "number": 6},
    {"width": 1, "height": 1, "x": 2, "y": 14, "color": "#FFFF00", "number": 7},
    {"width": 1, "height": 1, "x": 6, "y": 12, "color": "#FFFF00", "number": 11},
    {"width": 1, "height": 1, "x": 8, "y": 3, "color": "#FFFF00", "number": 16},
    {"width": 1, "height": 1, "x": 5, "y": 3, "color": "#FFFF00", "number": 15},
    {"width": 1, "height": 1, "x": 2, "y": 6, "color": "#FFFF00", "number": 12},
    {"width": 1, "height": 1, "x": 11, "y": 5, "color": "#FFFF00", "number": 14},
    {"width": 1, "height": 1, "x": 17, "y": 6, "color": "#FFFF00", "number": 13},
    {"width": 1, "height": 1, "x": 20, "y": 2, "color": "#FFFF00", "number": 17},
]

# Rojo #FF0000
# Verde #00FF00
# Lista de información de semáforos
semaforos_info = [
    {"width": 1, "height": 2, "x": 5, "y": 0, "color": "#00FF00"},
    {"width": 2, "height": 1, "x": 6, "y": 2, "color": "Red"},
    {"width": 2, "height": 1, "x": 0, "y": 6, "color": "Red"},
    {"width": 1, "height": 2, "x": 2, "y": 4, "color": "#00FF00"},
    {"width": 1, "height": 2, "x": 20, "y": 4, "color": "#00FF00"},
    {"width": 2, "height": 1, "x": 18, "y": 6, "color": "Red"},
    {"width": 1, "height": 2, "x": 20, "y": 10, "color": "#00FF00"},
    {"width": 2, "height": 1, "x": 18, "y": 12, "color": "Red"},
    {"width": 1, "height": 2, "x": 16, "y": 22, "color": "#00FF00"},
    {"width": 2, "height": 1, "x": 14, "y": 21, "color": "Red"},
    {"width": 2, "height": 1, "x": 5, "y": 21, "color": "Red"},
    {"width": 1, "height": 2, "x": 7, "y": 22, "color": "#00FF00"},
]

# Lista de información de direcciones
directions_info = [
    {"width": 1, "height": 1, "x": 0, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 1, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 2, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 3, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 4, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 5, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 6, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 7, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 8, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 9, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 10, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 11, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 12, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 13, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 14, "y": 0, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 15, "y": 0, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 16, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 17, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 18, "y": 0, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 19, "y": 0, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 20, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 21, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 22, "y": 0, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 23, "y": 0, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 1, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 2, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 4, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 23, "y": 5, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 23, "y": 6, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 7, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 8, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 9, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 10, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 23, "y": 11, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 23, "y": 12, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 13, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 14, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 15, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 16, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 17, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 19, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 22, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 23, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 22, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 21, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 23, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 18, "y": 23, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 17, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 16, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 15, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 14, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 13, "y": 23, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 23, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 11, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 8, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 7, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 5, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 1, "y": 23, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 0, "y": 23, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 22, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 20, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 19, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 17, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 16, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 14, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 13, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 11, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 10, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 9, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 0, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 0, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 5, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 4, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 3, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 0, "y": 1, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 22, "y": 1, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 1, "y": 22, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 2, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 3, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 4, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 5, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 6, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 7, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 8, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 9, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 10, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 11, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 12, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 13, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 14, "y": 1, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 15, "y": 1, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 16, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 17, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 18, "y": 1, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 19, "y": 1, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 20, "y": 1, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 21, "y": 1, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 22, "y": 2, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 4, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 22, "y": 5, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 22, "y": 6, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 7, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 8, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 9, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 10, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 22, "y": 11, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 22, "y": 12, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 13, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 14, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 22, "y": 15, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 16, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 17, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 19, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 22, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 21, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 22, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 18, "y": 22, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 17, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 16, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 15, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 14, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 13, "y": 22, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 22, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 11, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 8, "y": 22, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 7, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 5, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 22, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 1, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 20, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 19, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 17, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 16, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 14, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 1, "y": 13, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 11, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 10, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 9, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 1, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 1, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 6, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 1, "y": 5, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 4, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 3, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 1, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 2, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 7, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 5, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 5, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 3, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 7, "y": 3, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 6, "y": 4, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 6, "y": 5, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 6, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 6, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 7, "y": 4, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 7, "y": 5, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 7, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 7, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 5, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 5, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 5, "y": 19, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 5, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 6, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 6, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 6, "y": 19, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 6, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 18, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 20, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 18, "y": 19, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 17, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 16, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 14, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 13, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 20, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 19, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 19, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 17, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 16, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 14, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 13, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 18, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 18, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 18, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 18, "y": 2, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 19, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 19, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 19, "y": 2, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 21, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 17, "y": 5, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 16, "y": 5, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 21, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 17, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 16, "y": 4, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 12, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 5, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 4, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 3, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 7, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 6, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 5, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 4, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 3, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 2, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 14, "y": 7, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 6, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 5, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 4, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 2, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 7, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 6, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 5, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 4, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 3, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 2, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 12, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 20, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 19, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 17, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 16, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 14, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 13, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 21, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 20, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 19, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 18, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 17, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 16, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 15, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 14, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 13, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 13, "y": 12, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 14, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 19, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 17, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 16, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 15, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 14, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 13, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 14, "y": 12, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 21, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 20, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 19, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 18, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 17, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 16, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 15, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 14, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 13, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 15, "y": 12, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 11, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 8, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 7, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 17, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 5, "y": 17, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 4, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 17, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 11, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 16, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 8, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 7, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 5, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 16, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 21, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 18, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 17, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 16, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 21, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 20, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 19, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 18, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 17, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 16, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 21, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 20, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 19, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 18, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 17, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 16, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 21, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 20, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 19, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 18, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 17, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 16, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 11, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 8, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 7, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 11, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 5, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 11, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 11, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 10, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 9, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 8, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 7, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 6, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 5, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 4, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 3, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 2, "y": 10, "color": "#A9A9A9", "direction": "W"},
    {"width": 1, "height": 1, "x": 11, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 10, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 9, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 8, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 7, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 6, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 5, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 4, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 3, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 2, "y": 9, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 11, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 10, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 9, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 8, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 7, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 6, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 5, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 4, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 3, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 2, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 12, "y": 11, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 10, "color": "#A9A9A9", "direction": "SW"},
    {"width": 1, "height": 1, "x": 12, "y": 9, "color": "#A9A9A9", "direction": "S"},
    {"width": 1, "height": 1, "x": 12, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 13, "y": 8, "color": "#A9A9A9", "direction": "SE"},
    {"width": 1, "height": 1, "x": 14, "y": 8, "color": "#A9A9A9", "direction": "E"},
    {"width": 1, "height": 1, "x": 15, "y": 8, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 15, "y": 9, "color": "#A9A9A9", "direction": "NE"},
    {"width": 1, "height": 1, "x": 15, "y": 10, "color": "#A9A9A9", "direction": "N"},
    {"width": 1, "height": 1, "x": 15, "y": 11, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 14, "y": 11, "color": "#A9A9A9", "direction": "NW"},
    {"width": 1, "height": 1, "x": 13, "y": 11, "color": "#A9A9A9", "direction": "W"},

]

server = ModularServer(CityModel,
                       [canvas_element],
                       "City Model",
                       {"width": grid_width, "height": grid_height,
                        "buildings_info": buildings_info,
                        "specials_info": specials_info,
                        "semaforos_info": semaforos_info,
                        "directions_info": directions_info})

server.port = 8080
server.launch()
